### ISSUE TITLE
Battery Drainage

### ISSUE THREAD

**Issue by Sfreyjr** [jdev082/CatalystMobile#1]
A user i recommended this to stated they experienced higher battery loss while using it on mobile, Android 11. I believe they use Blackberry, and am waiting for confirmation. 
Edit: Nokia, hardware version 2.0, they said could be their hardware but it happened after installing Catalyst

**Comment by jdev082** [comment]
What battery capacity?

**Comment by Sfreyjr** [comment]
I’ll have them respond to the thread if they have a GH later

**Comment by PPPDUD** [comment]
Oof. Sounds like spyware. Tell them to download WorldExplorer from https://mojavesoft.net/worldbanner instead. Don't use Catalyst as a daily driver.

**Comment by jdev082** [comment]
> Oof. Sounds like spyware. Tell them to download WorldExplorer from https://mojavesoft.net/worldbanner instead. Don't use Catalyst as a daily driver.

Nobody can take you seriously at this point.

**Comment by Sfreyjr** [comment]
> Oof. Sounds like spyware. Tell them to download WorldExplorer from https://mojavesoft.net/worldbanner instead. Don't use Catalyst as a daily driver.

I wasn't even going to, but now I'm installing Catalyst everywhere.

**Comment by jdev082** [comment]
> > Oof. Sounds like spyware. Tell them to download WorldExplorer from https://mojavesoft.net/worldbanner instead. Don't use Catalyst as a daily driver.
> 
> I wasn't even going to, but now I'm installing Catalyst everywhere.

@PPPDUD Has done some outright stupid things such as:
- Making a custom license and made threats that he could never follow through with
- Making software proprietary and only providing Windows binaries to 'promote windows' (it was a 20 line python script compiled to an exe)

And the list goes on. And what they said earlier on the page we are discussing this on right now, is another thing he does. Take everything he says with a grain of salt. He is an internet troll, don't give him attention and he'll leave.

**Comment by Sfreyjr** [comment]
> > > Oof. Sounds like spyware. Tell them to download WorldExplorer from https://mojavesoft.net/worldbanner instead. Don't use Catalyst as a daily driver.
> > 
> > I wasn't even going to, but now I'm installing Catalyst everywhere.
> 
> @PPPDUD Has done some outright stupid things such as:
> - Making a custom license and made threats that he could never follow through with
> - Making software proprietary and only providing Windows binaries to 'promote windows' (it was a 20 line python script compiled to an exe)
> 
> And the list goes on. And what they said earlier on the page we are discussing this on right now, is another thing he does. Take everything he says with a grain of salt. He is an internet troll, don't give him attention and he'll leave.

I know. I was on the AT's

**Comment by andybrwr** [comment]
> Oof. Sounds like spyware. Tell them to download WorldExplorer from https://mojavesoft.net/worldbanner instead. Don't use Catalyst as a daily driver.

blud is stalking everyone atp ☠️☠️☠️

**Comment by jdev082** [comment]
> > Oof. Sounds like spyware. Tell them to download WorldExplorer from https://mojavesoft.net/worldbanner instead. Don't use Catalyst as a daily driver.
> 
> blud is stalking everyone atp skull_and_crossbonesskull_and_crossbonesskull_and_crossbones

i know right
